// WE WILL BE USING JAVASCRIPT FOR :
// GETTING THE INPUT FROM THE USER AND RESPOND IN THE REAL TIME
// GETTING THE INFORMATION OF THE BUTTON WHEN IT IS CLICKED
// GIVE THE ERROR MASSAGE WHENEVER THE LIMIT IS SET OUT OF THE BOND (OR THE REQUEST GO BEYOND THE LIMIT)
// AND CHANGING THE IMAGE IN EVERY SINGLE CLICK 



// the const in the data type and (btnE1) is the element and here we are targeting all the decument browser so  we are adding the ID of the button. TO get the direct value from the button.
const btnE1 = document.getElementById("btn");
//errormessage for the the erroe in the input size
const erorrMessageE1 = document.getElementById("errorMessage");
//getting the gallery id in the javascript
const galleryE1 = document.getElementById("gallery");

async function fetchImage(){
    // now here the funttion will be called and in the inspect window the output CLICKED will be show it will also show the number of time we will click the button.
    // console.log(clicked);
    // NOW FROM HERE WE ARE GOING TO USE THE UNSPLASH.COM API TO GENERATE RANDOM IMAGE.

    // get the value directly from the html page using getElementByTd
    const inputValue = document.getElementById("input").value;

    //to show the error mdg whenever the limit is out of bound
    if(inputValue> 10 || inputValue< 1){
        erorrMessageE1.style.display = "block";
        erorrMessageE1.innerText = "Number Should be between 0 to 11"
        return;
    }

    imgs = ""

    try {
        btnE1.style.display ="none";

        const loading = `<img src="Spinner.svg"/>`
        galleryE1.innerHTML = loading;
        //FETECH THE DATA AND THIS SHOULD BE DYNAMIC AS WE WANT DIFFERENT DATA FROM THE USER
        // and we want to fetch the data from the (veriable= inputValue(1-10))
        //
        // converting the data to the json file and [{(res)getting the response} and {(=>res) convering it to json(its like an array or format of the file)}]
        //.then(data) this will gives us data 
        await fetch(`https://api.unsplash.com/photos?per_page=${inputValue}&page=${Math.round(Math.random() * 1000)}&client_id=pbZHOd95LDDkOkZij4P_E86DGQL8Jo7lqPx65BfTY8o`).then((res)=>res.json().then((data)=>{
            //two get the url of image which are generated by the api and each type we will gat different images
                if(data){
                data.forEach((pic) => {
                    
                    imgs +=`<img src=${pic.urls.small} alt="images"/>
                    `;  
                    galleryE1.style.display= "block";
                    galleryE1.innerHTML = imgs; 
                    btnE1.style.display ="block";
                });
            }
        })
    
    );
    //when we dont need the error message 
    erorrMessageE1.style.display = "none";

        
    } catch (error) {
        erorrMessageE1.innerText="An error occurred , try after some time."
        btnE1.style.display ="block";
    }
    

}



// it will listen the every command of the botton
// and calling the funting fetchImage go give desired output
btnE1.addEventListener("click", fetchImage)